# 线性模型

> $ f(\bf{x}) = \bf{\omega}^T\bf{x} + b $

In [1]:
# 生成数据集
# y = lambda^T * x + b
import numpy as np

lambdas = np.array([0.4, 0.6, 0.1])
b = 0.7

x = np.array(
    [[0.1, 0.3, 0.6],
    [0.5, 0.7, 0.1],
    [0.9, 1.1, 3.1],
    [0.1, 0.5, 0.3],
    [0.9, 0.1, 0.0],
    [0.0, 0.3, -0.3],
    [0.3, 0.5, 0.1],
    [-0.5, 0.6, 0.2]])

y = np.dot(x, lambdas)+ b+ (np.random.rand(8)-0.5)*0.001



## 最小二乘法

> $ (\omega^*, b^*) = argmin_{(\omega,b)}\sum_{i=1}^{m}(y_i-\omega x_i-b)^2 $

> $ \omega = \omega + \alpha * (\omega \sum_{i=1}^{m}x_i^2 - \sum_{i=1}^{m}(y_i-b)x_i) $

> $ b = b + \alpha * (mb - \sum_{i=1}^{m}(y_i-\omega x_i)) $

#### 向量形式

> $ \omega^* = argmin_{\omega}(y-X\omega)^T(y-X\omega) $

> $ \omega = \omega + X^T(X\omega - y) $

In [207]:
def least_square_method(x, y, a=0.01, eps=1e-9, maxstep=1000):
    X = np.concatenate([x, np.ones((x.shape[0],1))], axis=1)
    w = np.random.rand(X.shape[1])
    w_0 = np.zeros(X.shape[1])
    step = 0
    obj_0 = 0
    obj = np.sum( (np.dot(X, w) - y)**2 )
    while (np.abs(obj_0-obj) > eps and step < maxstep):
        w_0 = w.copy()
        obj_0 = obj
        w = w - a * (np.dot(X.T, np.dot(X, w)-y))
        obj = np.sum( (np.dot(X, w) - y)**2 )
        # print (np.sum((w_0-w)**2))
        if step%(maxstep//100) ==0:
            print(w)
        step += 1
    return w
        
least_square_method(x,y,maxstep=100000)

[ 0.14068681  0.55193034  0.45331055  0.62897826]
[ 0.3957395   0.5793193   0.10530232  0.70923767]
[ 0.39942186  0.597373    0.10054259  0.70119047]


array([ 0.39997287,  0.60007552,  0.09983014,  0.6999859 ])

# 对数几率回归 logistic regression

> 不要轻易翻译为逻辑回归

> $ y = \frac{1}{1+e^{-z}} $

> 建立对数似然函数之后，求导得：

> $ \frac{\partial L}{\partial \theta} = \sum_{i=1}^{m} (y_i-\sigma(\theta^T x_i))x_i $

In [2]:
import pdb

def sigma(X):
    return 1/(1+np.e**(-X))
    
def logistic_regression(x, y, a=0.01, eps=1e-9, maxstep=1000, lambdas=0.8):
    dim = x.shape[1]
    theta = np.random.rand(dim)
    theta_0 = np.zeros(dim)
    obj = np.sum( (sigma(np.dot(x, theta)) -y)**2 ) + lambdas * np.sum(theta**2)
    obj_0 = 0
    step = 0
    while (np.abs(obj-obj_0) > eps) and step < maxstep:
        theta_0 = theta
        obj_0 = obj
        delta = np.dot((sigma(np.dot(x, theta)) - y) ,x) + lambdas * theta
        theta = theta - a * delta
        obj = np.sum( (sigma(np.dot(x, theta)) -y)**2 ) + lambdas * np.sum(theta**2)
        if step % (maxstep//100) == 0:
            print(obj, delta)
        step +=1
    print("Total step: %s" % step)
    return theta
        
y_logistic = (y > 1).astype('int')
logistic_regression(x, y_logistic, a=0.01, eps=1e-9, maxstep=10000)

2.47268674184 [-0.50324329 -0.00509019  0.85025005]
2.13259928572 [-0.19212312 -0.05048716  0.22859254]
2.19434270715 [-0.07080534 -0.02847948  0.05838228]
2.2365926134 [-0.02458731 -0.01127324  0.01711192]
2.25324557002 [-0.00833436 -0.00405399  0.00548152]
2.25911111708 [-0.00280117 -0.00141635  0.00182136]
2.26110885598 [-0.00093859 -0.00049048  0.00061326]
2.26178178776 [-0.00031411 -0.00016944  0.00020747]
2.2620075946 [ -1.05051433e-04  -5.85087959e-05   7.03137855e-05]
2.26208325563 [ -3.51183477e-05  -2.02092490e-05   2.38502032e-05]
2.26210859057 [ -1.17353153e-05  -6.98378321e-06   8.09408162e-06]
2.2621170705 [ -3.91998485e-06  -2.41475368e-06   2.74804685e-06]
2.2621199079 [ -1.30886745e-06  -8.35420461e-07   9.33363282e-07]
2.262120857 [ -4.36835726e-07  -2.89193868e-07   3.17136988e-07]
2.26212117437 [ -1.45726876e-07  -1.00166786e-07   1.07799268e-07]
Total step: 1453


array([ 1.02787742,  0.24836482,  0.29922371])

In [236]:
# from sklearn
import sklearn.linear_model
lr = sklearn.linear_model.LogisticRegression(verbose=1, random_state=np.random.randint(1000000), warm_start=True)
lr.fit(x, y_logistic)
lr.coef_

[LibLinear]

array([[ 0.87608388,  0.21525248,  0.28978609]])