## 神经元

In [2]:
import numpy as np
def sigmoid(X):
    return 1/(1+np.e**(-X))

In [3]:
# 数据集

from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
iris = load_iris()

train_X, test_X, train_Y, test_Y =  train_test_split(iris.data, iris.target, test_size=0.2)

## 感知机

In [4]:
def Perceptron(X, Y, alpha=0.01, threshold=1e-6, maxiter=100):
    Xh = np.concatenate([X, -np.ones([X.shape[0],1])], axis=1)
    W = np.zeros(Xh.shape[1])
    step =0
    cursor = 0
    delta_W = threshold + 1
    while np.sum(delta_W**2) > threshold and step <= maxiter:
        delta_W = alpha * (Y - sigmoid(np.dot(W, Xh.T)))[cursor] * Xh[cursor,:]
        W += delta_W
        step += 1
        cursor += 1
        if cursor >= Xh.shape[0]:
            cursor = 0
        print(W)
    return W

Perceptron(train_X, train_Y)
    

[ 0.108   0.054   0.0915  0.0375 -0.015 ]
[ 0.18154165  0.09016802  0.15057444  0.05920081 -0.02705601]
[ 0.25477426  0.12247653  0.2098067   0.08181677 -0.03782551]
[ 0.20218781  0.08621001  0.19892674  0.08000344 -0.02875888]
[ 0.16160822  0.06136536  0.18733257  0.07834713 -0.02047733]
[ 0.23920787  0.09219262  0.25430214  0.09748129 -0.03110742]
[ 0.29946306  0.12128134  0.30728515  0.12241448 -0.04149625]
[ 0.30109167  0.12202889  0.30835309  0.12276156 -0.04176323]
[ 0.3027141   0.12281113  0.30956991  0.12313819 -0.04205295]
[ 0.26125797  0.09036721  0.30055771  0.12133575 -0.03304075]
[ 0.32086852  0.11811695  0.35297388  0.14086334 -0.04331843]
[ 0.3224216   0.11879466  0.35401868  0.14114572 -0.04360081]
[ 0.38992012  0.15002531  0.41043535  0.1653243  -0.05367521]
[ 0.34402897  0.12038728  0.3951383   0.16341217 -0.04411456]
[ 0.40658504  0.14863841  0.44356881  0.18157361 -0.05420425]
[ 0.40688669  0.14878181  0.44380123  0.18164284 -0.0542537 ]


array([ 0.40688669,  0.14878181,  0.44380123,  0.18164284, -0.0542537 ])

## BP 算法

> 训练目标： $ E_k = \frac{1}{2} \sum_{j=1}^{l} (\hat{y}_j^k - y_j^k) $

> 更新公式： 

> $ \Delta \omega_{hj} = - \eta \frac{\partial E_k}{\partial \omega_{hj}} $

> $ = \eta g_j b_h  $

> 其中 $ g_j = \hat{y}_j^k(1-\hat{y}_j^h) (y_j^k-\hat{y}_k^k) $ , $ b_h $ 为隐层的输出

In [5]:
import numpy as np

def activate_function(X):
    return 1/(1+np.e**(-X))

def back_propagation(X, Y, rate=0.01):
    """
    三层网络，每层都是 sigmoid激活
    
       y      y      y
    
       omega1 * h - theta1
    
    h    h      h       h
    
        omega0 * h - theta0
        
       x      x      x
    
    """
    layer0 = X.shape[1]+1
    layer1 = X.shape[1]
    layer2 = Y.shape[1]
    
    X = np.concatenate([np.ones((X.shape[0],1)), X], axis=1)
    np.random.seed(seed=1000)
    omega0 = np.random.random((layer0, layer1))-0.5
    # theta0 = np.random.random(1)
    omega1 = np.random.random((layer1, layer2))-0.5
    # theta1 = np.random.random(1)
    # print(X)
    step = 0
    while (step < 1):
        _b = np.dot(X, omega0)
        b = activate_function(_b)
        # print(b)
        _y = np.dot(b, omega1)
        y = activate_function(_y)
        # print(y)
        g = np.sum(y*(1-y)*(Y-y), axis=0)
        print(g)
        omega1 += rate * g * b
        
        step +=1 

back_propagation(train_X, train_Y.reshape((train_Y.shape[0], 1)))





[ 13.94576393]


ValueError: operands could not be broadcast together with shapes (4,1) (120,4) (4,1) 

In [ ]:
train_X.shape