## 神经元

In [1]:
import numpy as np
def sigmoid(X):
    return 1/(1+np.e**(-X))

## 感知机

In [8]:
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
iris = load_iris()

train_X, test_X, train_Y, test_Y =  train_test_split(iris.data, iris.target, test_size=0.2)

In [42]:
def Perceptron(X, Y, alpha=0.01, threshold=1e-6, maxiter=100):
    Xh = np.concatenate([X, -np.ones([X.shape[0],1])], axis=1)
    W = np.zeros(Xh.shape[1])
    step =0
    cursor = 0
    delta_W = threshold + 1
    while np.sum(delta_W**2) > threshold and step <= maxiter:
        delta_W = alpha * (Y - sigmoid(np.dot(W, Xh.T)))[cursor] * Xh[cursor,:]
        W += delta_W
        step += 1
        cursor += 1
        if cursor >= Xh.shape[0]:
            cursor = 0
        print(W)
    return W

Perceptron(train_X, train_Y)
    

[ 0.025   0.01    0.0175  0.005  -0.005 ]
[ 0.09557705  0.0460087   0.08231566  0.02948592 -0.01940348]
[ 0.06617603  0.02462614  0.07362899  0.02814951 -0.01272143]
[ 0.03309131  0.00235757  0.06408532  0.02687702 -0.00635898]
[ 0.11775316  0.0480481   0.13934031  0.05912915 -0.01979737]
[ 0.18304506  0.08069405  0.19647071  0.08244769 -0.03145664]
[ 0.18843154  0.08321353  0.2002065   0.08357711 -0.03232543]
[ 0.2683763   0.11228435  0.26976882  0.10434198 -0.04270786]
[ 0.21915171  0.07855639  0.25609533  0.10251885 -0.0335922 ]
[ 0.17490333  0.04558701  0.24221348  0.10078362 -0.02491605]
[ 0.13619343  0.0181675   0.22931018  0.09917071 -0.01685148]
[ 0.14309729  0.02143114  0.23483327  0.100677   -0.01810673]
[ 0.10210159 -0.0071885   0.22323071  0.09913    -0.01037169]
[ 0.16659037  0.02109605  0.27979982  0.12175764 -0.02168551]
[ 0.1327279  -0.00199199  0.269795    0.12021844 -0.0139895 ]
[ 0.0956177  -0.02796914  0.26014635  0.11799182 -0.00656746]
[ 0.06108286 -0.05145283  0.

array([ 0.26237026, -0.05156869,  0.58859262,  0.25205508, -0.01525132])

## BP 算法

In [43]:
def activate_function()

def back_propagation(X, Y):
    
    pass



